name               : Diogo C. Ribeiro
description         : Studying Black Holes

email: dribeiro@mpe.mpg.de
github_user: diogoribeiro98
google_scholar: https://scholar.google.com/citations?user=cYXGWRUAAAAJ&hl=en
